// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"employee-service/pkg/api"
	"employee-service/pkg/api/service"
	"employee-service/pkg/config"
	"employee-service/pkg/service/random"
	"employee-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	randomGenerator, err := random.NewRandomGenerator()
	if err != nil {
		return nil, err
	}
	employeeUseCase := usecase.NewEmployeeUseCase(randomGenerator)
	employeeServiceServer := service.NewAuthServiceServer(employeeUseCase)
	server, err := api.NewServerGRPC(cfg, employeeServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
